/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controller.ParCombo;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Database.Query;


/**
 *
 * @author clockwork
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    private String consulta = "select id_reporte, fecha_primera_dosis , fecha_segunda_dosis, paciente.nombre_paciente, paciente.paciente_apellido, paciente.edad, vacuna.nombre_vacuna from reportes inner join paciente on reportes.identificacion_vacuna = paciente.identificacion_paciente inner join vacuna on reportes.id_vacuna_usuario = vacuna.id_vacuna";
    public Reportes() {
        initComponents();
        this.cargar_tabla();
    }
    
    private void cargar_tabla(){
          
        try {            
            DefaultTableModel modelo = new DefaultTableModel();
            jTable1.setModel(modelo);
            ResultSet load = Query.read(consulta);
            ResultSetMetaData rmsd = load.getMetaData();
            int cantidad = rmsd.getColumnCount();
            String [] Columnas = {"id_reporte", "fecha_primera_dosis","fecha_segunda_dosis","nombre_paciente" ,"paciente_apellido", "edad", "nombre_vacuna"};
            for (int i = 0; i < Columnas.length; i++) {
                modelo.addColumn(Columnas[i]);               
            }
            while(load.next())
            {
                 Object[] filas = new Object[cantidad];
                 for (int i = 0; i < cantidad; i++) {
                     filas[i] = load.getObject(i + 1);
                 }
                 modelo.addRow(filas);
                
            }
            
        } catch (Exception e) {
        }
        
    }
    
    public void filtrar(String text){
        String [] Columnas =  {"id_reporte", "fecha_primera_dosis","fecha_segunda_dosis","nombre_paciente" ,"paciente_apellido", "edad", "nombre_vacuna"};
        Query.buscar(jTable1, text, Columnas,  consulta);
    }
    
    private void generar_reporte(){
        try {
             ResultSet ms = Query.Factura(consulta);
             while (ms.next()) {                
                 String id_reporte = ms.getString(1);
                 String fecha_primera_dosis = ms.getString(2);
                 String fecha_segunda_dosis = ms.getString(3);
                 String nombre_paciente = ms.getString(4);                  
                 String paciente_apellido = ms.getString(5);
                 String edad = ms.getString(6);
                 String nombre_vacuna = ms.getString(7);
                 String factura = "############## La secretaría de salud municipal ###########\n"
						+ "########## centro de salud  ########\n\n"
						+ " Lo\n" +" informacion de usuario  \n\n"
						+ "  municipal  Florencia \n"
						+ "\n=============== R E P O R T E ==============\n\n"                                                
                                                + "id reporte  : " + id_reporte + "\n"                                                
                                                + "Fecha de primea dosis  : " + fecha_primera_dosis + "\n"
						+ "Fecha de segunda dosis : " + fecha_segunda_dosis + "\n"
                                                + "nombre del usuario : " + nombre_paciente + "\n"
                                                + "apellido del usuario : " + paciente_apellido + "\n"
						+ "edad: " + edad + "\n"						                                                
                                               	+ "\n============== DETALLES =============\n\n"
                                                + "nombre de la vacuna : " + nombre_vacuna ;
                 JOptionPane.showMessageDialog(null, factura, " Reporte " , JOptionPane.INFORMATION_MESSAGE);
                         
                
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtBuscar1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtBuscar1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TxtBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscar1ActionPerformed(evt);
            }
        });
        TxtBuscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBuscar1KeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Buscar : ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_reporte", "fecha_primera_dosis", "fecha_segunda_dosis", "nombre_paciente", "paciente_apellido", "edad", "nombre_vacuna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jMenu5.setText("Menu");

        jMenuItem1.setText("ir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar3.add(jMenu5);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TxtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscar1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Menu exe = new Menu();
        exe.setVisible(true);
        hide();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TxtBuscar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscar1KeyReleased
        // TODO add your handling code here:
        this.filtrar(TxtBuscar1.getText());
    }//GEN-LAST:event_TxtBuscar1KeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        this.generar_reporte();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtBuscar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
